// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "/Users/peetstander/Projects/omni-starter/app.config";
import type { default as appConfig1 } from "/Users/peetstander/Projects/omni-starter/node_modules/.c12/github_PartnersInBiz_omni_PfeSC7yUFf/app.config";
import type { default as appConfig2 } from "/Users/peetstander/Projects/omni-starter/node_modules/.pnpm/@shuriken-ui+nuxt@3.0.4_nuxt@3.11.1/node_modules/@shuriken-ui/nuxt/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1, typeof appConfig2]>

declare module 'nitropack' {
  interface AppConfig extends UserAppConfig {}
}
    
export {}